import { ResponseWebApi } from '@core/interfaces/base/responseWebApi.interface';
export const activeStateResponse: ResponseWebApi = {
  "message": "Registro activado correctamente",
  "status": true,
  "data": {
      "id": 677,
      "primerNombre": "PRUEBA2",
      "segundoNombre": "PRUEBA2",
      "primerApellido": "PRUEBA2",
      "segundoApellido": "PRUEBA2",
      "nombreCompleto": "PRUEBA2 PRUEBA2 PRUEBA2 PRUEBA2",
      "indicativoTelefono": 57,
      "telefono": "323",
      "indicativoCelular": 57,
      "celular": "562",
      "userName": "pprueba27667",
      "email": "aaq@g.com",
      "password": null,
      "imagenAvatar": {
          "url": "assets/images/svg/10.svg",
          "archivo": "",
          "nombre": "",
          "ruta": null,
          "rutaStorage": null,
          "idDocumento": null,
          "idEntidad": null,
          "size": null,
          "contentType": null
      },
      "imagenHuella": {
          "url": null,
          "archivo": "",
          "nombre": "",
          "ruta": null,
          "rutaStorage": null,
          "idDocumento": null,
          "idEntidad": null,
          "size": null,
          "contentType": null
      },
      "rutaHuella": null,
      "idEmpresa": 0,
      "idPais": 311,
      "idDepartamento": 2,
      "idCiudad": 81,
      "idBarrio": 0,
      "direccion": "3232",
      "idTipoIdentificacion": 8,
      "identificacion": "767667",
      "tiempoCambioClave": 15,
      "idTipoUsuario": 349,
      "idCliente": 12,
      "usuariosPerfiles": [
          {
              "idUsuario": 677,
              "idPerfil": 1,
              "nombrePerfil": "Super Admin",
              "nombrePais": null,
              "porDefecto": true,
              "fechaCreacion": "2021-03-05T15:18:08.133",
              "creadoPor": 1,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "usuariosEmpresas": [
          {
              "idUsuario": 677,
              "idEmpresa": 91,
              "nombreEmpresa": "Cubo SAS",
              "identificacion": "656776",
              "nombrePais": null,
              "porDefecto": true,
              "fechaCreacion": "2022-09-26T13:48:49.4333333",
              "creadoPor": 20,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "usuariosAgencias": [
          {
              "idUsuario": 677,
              "idAgencia": 529,
              "nombreAgencia": "MEDELLIN",
              "nombreCiudad": null,
              "direccion": "",
              "porDefecto": true,
              "fechaCreacion": "2022-01-03T11:43:23",
              "creadoPor": 1,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "historialMovimientos": [],
      "nombreEmpresa": null,
      "urlFirmaDigital": null,
      "version": 0,
      "idTercero": null,
      "idAgencia": 0,
      "codigoCliente": null,
      "codigoAgencia": null,
      "codigoEmpresa": null,
      "idAfiliado": 0,
      "intentosFallidos": null,
      "cargo": "NA",
      "fechaCreacion": "2022-09-26T15:27:49.9166667",
      "creadoPor": 20,
      "fechaModificacion": "2022-11-22T09:40:45.83",
      "modificadoPor": 17,
      "fechaAnulacion": null,
      "anuladoPor": 0,
      "estadoRegistro": "A",
      "observacionEstado": "a"
  }
}
export const inactiveStateResponse: ResponseWebApi = {
  "message": "Registro inactivado correctamente",
  "status": true,
  "data": {
      "id": 677,
      "primerNombre": "PRUEBA2",
      "segundoNombre": "PRUEBA2",
      "primerApellido": "PRUEBA2",
      "segundoApellido": "PRUEBA2",
      "nombreCompleto": "PRUEBA2 PRUEBA2 PRUEBA2 PRUEBA2",
      "indicativoTelefono": 57,
      "telefono": "323",
      "indicativoCelular": 57,
      "celular": "562",
      "userName": "pprueba27667",
      "email": "aaq@g.com",
      "password": null,
      "imagenAvatar": {
          "url": "assets/images/svg/10.svg",
          "archivo": "",
          "nombre": "",
          "ruta": null,
          "rutaStorage": null,
          "idDocumento": null,
          "idEntidad": null,
          "size": null,
          "contentType": null
      },
      "imagenHuella": {
          "url": null,
          "archivo": "",
          "nombre": "",
          "ruta": null,
          "rutaStorage": null,
          "idDocumento": null,
          "idEntidad": null,
          "size": null,
          "contentType": null
      },
      "rutaHuella": null,
      "idEmpresa": 0,
      "idPais": 311,
      "idDepartamento": 2,
      "idCiudad": 81,
      "idBarrio": 0,
      "direccion": "3232",
      "idTipoIdentificacion": 8,
      "identificacion": "767667",
      "tiempoCambioClave": 15,
      "idTipoUsuario": 349,
      "idCliente": 12,
      "usuariosPerfiles": [
          {
              "idUsuario": 677,
              "idPerfil": 1,
              "nombrePerfil": "Super Admin",
              "nombrePais": null,
              "porDefecto": true,
              "fechaCreacion": "2021-03-05T15:18:08.133",
              "creadoPor": 1,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "usuariosEmpresas": [
          {
              "idUsuario": 677,
              "idEmpresa": 91,
              "nombreEmpresa": "Cubo SAS",
              "identificacion": "656776",
              "nombrePais": null,
              "porDefecto": true,
              "fechaCreacion": "2022-09-26T13:48:49.4333333",
              "creadoPor": 20,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "usuariosAgencias": [
          {
              "idUsuario": 677,
              "idAgencia": 529,
              "nombreAgencia": "MEDELLIN",
              "nombreCiudad": null,
              "direccion": "",
              "porDefecto": true,
              "fechaCreacion": "2022-01-03T11:43:23",
              "creadoPor": 1,
              "fechaModificacion": null,
              "modificadoPor": 0,
              "fechaAnulacion": null,
              "anuladoPor": 0,
              "estadoRegistro": "A",
              "observacionEstado": null
          }
      ],
      "historialMovimientos": [],
      "nombreEmpresa": null,
      "urlFirmaDigital": null,
      "version": 0,
      "idTercero": null,
      "idAgencia": 0,
      "codigoCliente": null,
      "codigoAgencia": null,
      "codigoEmpresa": null,
      "idAfiliado": 0,
      "intentosFallidos": null,
      "cargo": "NA",
      "fechaCreacion": "2022-09-26T15:27:49.9166667",
      "creadoPor": 20,
      "fechaModificacion": "2022-11-22T09:40:10.07",
      "modificadoPor": 17,
      "fechaAnulacion": "2022-11-22T09:40:10.07",
      "anuladoPor": 17,
      "estadoRegistro": "I",
      "observacionEstado": "i"
  }
}
