import { ResponseWebApi } from './../interfaces/base/responseWebApi.interface';

export const editarUsuarioResponse: ResponseWebApi = {
  "message": "Registro editado correctamente",
  "status": true,
  "data": {
    "id": 683,
    "primerNombre": "angie",
    "segundoNombre": "paola",
    "primerApellido": "arrieta",
    "segundoApellido": "mendoza",
    "nombreCompleto": "angie paola arrieta mendoza",
    "indicativoTelefono": 57,
    "telefono": "6456456452",
    "indicativoCelular": 56,
    "celular": "36456345",
    "userName": "aarrieta5344",
    "email": "angie@gmail.cpm",
    "password": null,
    "imagenAvatar": {
      "url": "https://brasiliastorage.blob.core.windows.net/seguridad-qas/Avatars%2FsuperTransporte_11_23_2022_12_30_12_5955955.png",
      "archivo": "",
      "nombre": "",
      "ruta": null,
      "rutaStorage": null,
      "idDocumento": null,
      "idEntidad": null,
      "size": null,
      "contentType": null
    },
    "imagenHuella": {
      "url": null,
      "archivo": "",
      "nombre": "",
      "ruta": null,
      "rutaStorage": null,
      "idDocumento": null,
      "idEntidad": null,
      "size": null,
      "contentType": null
    },
    "rutaHuella": null,
    "idEmpresa": 0,
    "idPais": 311,
    "idDepartamento": 41,
    "idCiudad": 1060,
    "idBarrio": 0,
    "direccion": "calle 3",
    "idTipoIdentificacion": 8,
    "identificacion": "5344",
    "tiempoCambioClave": 15,
    "idTipoUsuario": 349,
    "idCliente": 12,
    "usuariosPerfiles": [
      {
        "idUsuario": 683,
        "idPerfil": 1,
        "nombrePerfil": "Super Admin",
        "nombrePais": null,
        "porDefecto": true,
        "fechaCreacion": "2022-11-23T07:31:19.4466667",
        "creadoPor": 17,
        "fechaModificacion": null,
        "modificadoPor": 0,
        "fechaAnulacion": null,
        "anuladoPor": 0,
        "estadoRegistro": "A",
        "observacionEstado": null
      }
    ],
    "usuariosEmpresas": [
      {
        "idUsuario": 683,
        "idEmpresa": 15,
        "nombreEmpresa": "Consware - Admin",
        "identificacion": "111111111",
        "nombrePais": null,
        "porDefecto": true,
        "fechaCreacion": "2022-11-23T07:31:19.4466667",
        "creadoPor": 17,
        "fechaModificacion": null,
        "modificadoPor": 0,
        "fechaAnulacion": null,
        "anuladoPor": 0,
        "estadoRegistro": "A",
        "observacionEstado": null
      }
    ],
    "usuariosAgencias": [
      {
        "idUsuario": 683,
        "idAgencia": 989,
        "nombreAgencia": "prueba1",
        "nombreCiudad": null,
        "direccion": "",
        "porDefecto": true,
        "fechaCreacion": "2022-11-23T07:31:19.4466667",
        "creadoPor": 17,
        "fechaModificacion": null,
        "modificadoPor": 0,
        "fechaAnulacion": null,
        "anuladoPor": 0,
        "estadoRegistro": "A",
        "observacionEstado": null
      }
    ],
    "historialMovimientos": [],
    "nombreEmpresa": null,
    "urlFirmaDigital": null,
    "version": 0,
    "idTercero": null,
    "idAgencia": 0,
    "codigoCliente": null,
    "codigoAgencia": null,
    "codigoEmpresa": null,
    "idAfiliado": 0,
    "intentosFallidos": null,
    "cargo": "ing",
    "fechaCreacion": "2022-11-23T07:30:12.5466667",
    "creadoPor": 17,
    "fechaModificacion": "2022-11-23T07:31:19.4466667",
    "modificadoPor": 17,
    "fechaAnulacion": null,
    "anuladoPor": 0,
    "estadoRegistro": "A",
    "observacionEstado": null
  }
}
