export class DetalleArchivoDespachoSicom {
    fechaCreacion: Date = null;
    creadoPor: 0;
    fechaModificacion: Date = null;
    modificadoPor: 0;
    fechaAnulacion: Date = null;
    anuladoPor: 0;
    estadoRegistro: '';
    observacionEstado: '';
    id: 0;
    idArchivoDespachoSicom: 0;
    periodo: '';
    codigoSicomMinorista: '';
    nombreComercialPropietario: '';
    razonSocialPropietario: '';
    nitPropietario: '';
    nombreComercialOperador: '';
    razonSocialOperador: '';
    nitOperador: '';
    idDepartamento: 0;
    departamento: '';
    idCiudad: 0;
    municipio: '';
    idMayorista: 0;
    codigoSicomMayorista: '';
    nombreDistribuidorMayorista: '';
    codigoSicomPlantaAbastecimiento: '';
    nombrePlantaAbastecimiento: '';
    idDepartamentoPlantaAbastecimiento: 0;
    departamentoPlantaAbastecimiento: '';
    idCiudadPlantaAbastecimiento: 0;
    municipioPlantaAbastecimiento: '';
    direccionPlantaAbastecimiento: '';
    idTipoProducto: 0;
    producto: '';
    galonesDespachados: 0;
    margenParaCalculo: 0;
    baseParaCalculo: 0;
    montoCalculado: 0;
    estado = '';
    observaciones: '';
    cantidadGMC : 0;
    cantidadGME : 0;
    cantidadACPM : 0;
    galonesSicom : 0;
    recaudoSicom : 0;
    nombreMayorista : '';
}
